language: python
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install coveralls pytest
  - pip install -r requirements.txt
  - python setup.py install
script: pytest
after_success: coveralls --data_file=.coverage
