site_name: "Codext - Extension of native codecs"
repo_url: https://github.com/dhondta/python-codext
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - Features: features.md
  - Encodings:
    - 'Base': base.md
    - 'Binary': binary.md
    - 'Common': common.md
    - 'Crypto ciphers': ciphers.md
    - 'Languages': languages.md
    - 'Others': others.md
    - 'Steganography': stegano.md
  - 'String manipulations': manipulations.md
  - 'CLI tool': cli.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
