site_name: "Codext - Extension of native codecs for Python"
repo_url: https://github.com/dhondta/python-codext
site_author: dhondta
docs_dir: docs
nav:
  - Introduction: index.md
  - Features: features.md
  - 'Guess mode': guessing.md
  - Encodings:
    - Base: enc/base.md
    - Binary: enc/binary.md
    - Common: enc/common.md
    - Compressions: enc/compressions.md
    - Cryptography: enc/crypto.md
    - Hashing: enc/hashing.md
    - Languages: enc/languages.md
    - Others: enc/others.md
    - Steganography: enc/stegano.md
  - 'String manipulations': manipulations.md
  - 'CLI tool': cli.md
  - 'Create your codec': howto.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
